// <auto-generated />
using System;
using BarcaLog.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarcaLog.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(BarcaLogDbContext))]
    partial class BarcaLogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BarcaLog.Domain.Entidades.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Carga")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time");

                    b.Property<string>("JanelaConformidade")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Motorista")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TerminalId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("TransportadoraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Placa");

                    b.HasIndex("TransportadoraId");

                    b.HasIndex("Data", "Hora");

                    b.HasIndex("TerminalId", "Data");

                    b.ToTable("Agendamentos", (string)null);
                });

            modelBuilder.Entity("BarcaLog.Domain.Entidades.Condutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PlacaVinculada")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StatusNegativacao")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("TransportadoraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlacaVinculada");

                    b.HasIndex("TransportadoraId");

                    b.ToTable("Condutores", (string)null);
                });

            modelBuilder.Entity("BarcaLog.Domain.Entidades.Contestacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Justificativa")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("OcorrenciaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RespondidoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("RespostaOperador")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("TransportadoraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransportadoraId");

                    b.HasIndex("OcorrenciaId", "Status");

                    b.ToTable("Contestacoes", (string)null);
                });

            modelBuilder.Entity("BarcaLog.Domain.Entidades.LogAuditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Detalhes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Quando")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Acao");

                    b.HasIndex("Autor");

                    b.HasIndex("Quando");

                    b.ToTable("LogsAuditoria", (string)null);
                });

            modelBuilder.Entity("BarcaLog.Domain.Entidades.Marcacao", b =>
                {
                    b.Property<string>("MovimentoId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Carga")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Ciclo")
                        .HasColumnType("int");

                    b.Property<string>("CodConvenio")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Convenio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DataLiberacao")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("DataMarcacao")
                        .HasColumnType("datetime2(0)");

                    b.Property<decimal?>("EsperaHoras")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(10,2)")
                        .HasComputedColumnSql("CONVERT(decimal(10,2), ROUND(DATEDIFF(SECOND, [DataMarcacao], [DataLiberacao]) / 3600.0, 2))", true);

                    b.Property<string>("Operador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TerminalId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("MovimentoId");

                    b.HasIndex("Convenio");

                    b.HasIndex("DataMarcacao");

                    b.HasIndex("Senha");

                    b.HasIndex("TerminalId", "DataMarcacao");

                    b.ToTable("Marcacoes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Marcacoes_Liberacao", "[DataLiberacao] IS NULL OR [DataLiberacao] >= [DataMarcacao]");
                        });
                });

            modelBuilder.Entity("BarcaLog.Domain.Entidades.Ocorrencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CondutorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Local")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Responsavel")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("TransportadoraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CondutorId");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("Placa");

                    b.HasIndex("TransportadoraId", "Nivel", "CriadoEm");

                    b.ToTable("Ocorrencias", (string)null);
                });

            modelBuilder.Entity("BarcaLog.Domain.Entidades.Terminal", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("CapacidadeDiariaCarretas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1000);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Terminais", null, t =>
                        {
                            t.HasCheckConstraint("CK_Terminais_Capacidade", "[CapacidadeDiariaCarretas] > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = "unitapajos",
                            CapacidadeDiariaCarretas = 1000,
                            Nome = "Unitapajós"
                        },
                        new
                        {
                            Id = "tgpm",
                            CapacidadeDiariaCarretas = 1000,
                            Nome = "TGPM"
                        },
                        new
                        {
                            Id = "hidrovias",
                            CapacidadeDiariaCarretas = 1000,
                            Nome = "Hidrovias"
                        });
                });

            modelBuilder.Entity("BarcaLog.Domain.Entidades.Transportadora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Transportadoras", (string)null);
                });

            modelBuilder.Entity("BarcaLog.Domain.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("BarcaLog.Domain.Entidades.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StatusNegativacao")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("StatusPortaria")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("StatusPortariaDesde")
                        .HasColumnType("datetime2");

                    b.Property<string>("TerminalId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("TransportadoraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.HasIndex("StatusNegativacao");

                    b.HasIndex("TerminalId");

                    b.HasIndex("TransportadoraId");

                    b.HasIndex("StatusPortaria", "StatusPortariaDesde");

                    b.ToTable("Veiculos", (string)null);
                });

            modelBuilder.Entity("BarcaLog.Domain.Entidades.Agendamento", b =>
                {
                    b.HasOne("BarcaLog.Domain.Entidades.Terminal", "Terminal")
                        .WithMany()
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarcaLog.Domain.Entidades.Transportadora", "Transportadora")
                        .WithMany()
                        .HasForeignKey("TransportadoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Terminal");

                    b.Navigation("Transportadora");
                });

            modelBuilder.Entity("BarcaLog.Domain.Entidades.Condutor", b =>
                {
                    b.HasOne("BarcaLog.Domain.Entidades.Transportadora", "Transportadora")
                        .WithMany("Condutores")
                        .HasForeignKey("TransportadoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Transportadora");
                });

            modelBuilder.Entity("BarcaLog.Domain.Entidades.Contestacao", b =>
                {
                    b.HasOne("BarcaLog.Domain.Entidades.Ocorrencia", "Ocorrencia")
                        .WithMany()
                        .HasForeignKey("OcorrenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarcaLog.Domain.Entidades.Transportadora", "Transportadora")
                        .WithMany()
                        .HasForeignKey("TransportadoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ocorrencia");

                    b.Navigation("Transportadora");
                });

            modelBuilder.Entity("BarcaLog.Domain.Entidades.Marcacao", b =>
                {
                    b.HasOne("BarcaLog.Domain.Entidades.Terminal", "Terminal")
                        .WithMany()
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("BarcaLog.Domain.Entidades.Ocorrencia", b =>
                {
                    b.HasOne("BarcaLog.Domain.Entidades.Condutor", "Condutor")
                        .WithMany()
                        .HasForeignKey("CondutorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BarcaLog.Domain.Entidades.Transportadora", "Transportadora")
                        .WithMany()
                        .HasForeignKey("TransportadoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Condutor");

                    b.Navigation("Transportadora");
                });

            modelBuilder.Entity("BarcaLog.Domain.Entidades.Veiculo", b =>
                {
                    b.HasOne("BarcaLog.Domain.Entidades.Terminal", "Terminal")
                        .WithMany()
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarcaLog.Domain.Entidades.Transportadora", "Transportadora")
                        .WithMany("Veiculos")
                        .HasForeignKey("TransportadoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Terminal");

                    b.Navigation("Transportadora");
                });

            modelBuilder.Entity("BarcaLog.Domain.Entidades.Transportadora", b =>
                {
                    b.Navigation("Condutores");

                    b.Navigation("Veiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
